theme: jekyll-theme-so-simple
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Holistic Mama Living"
description: "A cozy space for mindful mamas embracing natural parenting, holistic wellness, and sustainable living."
baseurl: "" # leave empty unless you're using a subpath
url: "https://yourusername.github.io" # replace with your GitHub username if needed
logo: "/assets/images/logo.png" # optional, update when you add a logo
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

google_analytics: # optional
disqus:
  shortname: # optional
twitter:
  username: holisticmamalife # optional

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination
paginate: 6
paginate_path: /page:num/

# Search
search_full_content: false

# Category and tag archive paths (can be enabled later if needed)
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

author:
  name: Rebecca
  email: your@email.com
  picture: /assets/images/rebecca.jpg # optional
  bio: Holistic mama, herbal tea lover, and homeschooling soul.
  location: North Carolina
  twitter: holisticmamalife
  links:
    - title: Instagram
      url: https://instagram.com/holistic.mama.living
      icon: fab fa-instagram
    - title: Pinterest
      url: https://pinterest.com/holisticmamaliving
      icon: fab fa-pinterest

# Navigation links (visible in menu)
navigation:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
  - title: Natural Parenting
    url: /natural-parenting/
  - title: Clean Living
    url: /clean-living/
  - title: Holistic Nutrition
    url: /holistic-nutrition/
  - title: Mindful Motherhood
    url: /mindful-motherhood/
  - title: Natural Remedies
    url: /natural-remedies/
  - title: Sustainable Living
    url: /sustainable-living/
  - title: Homeschooling & Rhythms
    url: /homeschooling/
  - title: Fertility, Birth & Postpartum
    url: /fertility-postpartum/

# Footer links (icons optional)
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
