# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Holistic Mama Living"
description: "A peaceful space for mindful motherhood, holistic wellness, and intentional living."
baseurl: ""
url: "https://rebecca-ro.github.io/holisticmamaliving"
logo: "/assets/images/logo.png"
date_format: "%B %-d, %Y"
read_time: "true"
words_per_minute: 200
mathjax:
  enable: # MathJax equations, e.g. true, false (default)
  combo:  # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags:  # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination
paginate: 6
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
name: Rebecca
  email: rebecca.ro2001@gmail.com
  picture: /assets/images/rebecca.jpg
  bio: Holistic mama, herbal tea lover, embracing wellness, nature, and intentional living.
  location: North Carolina
  links:
    - title: Pinterest
      url: https://pinterest.com/holisticmamaliving
      icon: fab fa-pinterest

# Navigation links (visible in menu)
navigation:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
  - title: Natural Parenting
    url: /natural-parenting/
  - title: Clean Living
    url: /clean-living/
  - title: Holistic Nutrition
    url: /holistic-nutrition/
  - title: Mindful Motherhood
    url: /mindful-motherhood/
  - title: Natural Remedies
    url: /natural-remedies/
  - title: Sustainable Living
    url: /sustainable-living/
  - title: Homeschooling & Rhythms
    url: /homeschooling/
  - title: Birth & Postpartum
    url: /birth-postpartum/


# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
